version: '2'
services:
  tomcat:
    image: tomcat
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
  tomcat-lb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 8080:8080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'